output "Your_website_can_be_accessed_at" {
  description = "record name"
  value       = "https://${aws_route53_record.www.name}"
}

output "bastion_host_public_ip" {
  description = "public ip of bastion_host"
  value       = aws_instance.bastion_host.public_ip
}

output "ssh_keypair_filename_to_access_servers" {
  description = "ssh key generated by terraform"
  value       = var.generated_key_name
}


