variable "instance_type" {
  description = "type of ec2 instance"
  type        = string
  default     = "t3.micro" //t2.micro not supported in canada asg
}

variable "bastion_instance_type" {
  description = "type of ec2 instance"
  type        = string
  default     = "t2.micro" //t2.micro not supported in canada asg
}

variable "generated_key_name" {
  description = "Key-pair generated by Terraform for bastion and auto scaling instances"
  type        = string
  default     = "terraform-key-pair"
}